### ISSUE TITLE
Problème d'accès à l'API Cooptel

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/applets-java-api#13]
Signalés par plusieurs utilisateurs récemment, les problèmes d'accès à l'API Cooptel pour visualiser la consommation internet des résidences étudiantes semblent toucher toutes les plateformes réalisées par les étudiants.

L'onglet "[Voir ma consommation](http://www2.cooptel.qc.ca/services/temps/index.php)" fonctionne toujours sur Cooptel. Les identifiants à utiliser sont de la forme suivante : 

> - Votre nom d’utilisateur est votre numéro de résidence, suivi de votre numéro de local. Vous
devez obligatoirement utiliser la forme suivante : ets-res1-100. Si vous habitez le local 105
de la résidence 2, votre nom d’utilisateur sera ets-res2-105. Ne pas utiliser de majuscules.
> - Votre mot de passe est votre numéro de local. Vous devez obligatoirement utiliser la forme
suivante : ets100. Si vous habitez le local 105, que ce soit dans les résidences 1, 2 ou 3, votre
mot de passe sera ets105. Ne pas utiliser de majuscules.

([source](https://www.etsmtl.ca/Futurs-etudiants/Baccalaureat/Residences-universitaires/Avant-votre-arrivee/Info_residences.pdf))

Il y a probablement un problème avec les mécanismes d'[authentification](https://github.com/ApplETS/applets-java-api/blob/master/src/main/java/applets/etsmtl/ca/cooptel/CooptelResource.java#L52) qui fonctionnaient auparavant mais qui ont dû changer.

**Comment by gnut3ll4** [comment]
Le problème a été résolu ici : https://github.com/scarpentier/ETS-Rez-Net-Usage/commit/ebd6ab70885b2e791df686788dff0988be96c97a

**Comment by mikefaille** [comment]
@cmccauley Tu as aussi fixé Applets mec
